# Generated by Django 4.0.6 on 2022-07-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField(blank=True, null=True)),
                ('waktu_dibuat', models.DateField(auto_now=True)),
                ('waktu_terakhir_diedit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
